stages:
  - pre-check
  - build
  - test

variables:
  SEQUOIA_CRYPTO_POLICY: ""
  RUN_CLIPPY: "false"
  RUN_WINDOWS: "false"

include:
  - component: "gitlab.com/sequoia-pgp/common-ci/sequoia-pipeline@dvn0/add-alpine"

.gpg_agent:
  check:
    # The tests rely on gpg-agent.  Make sure it is available.
    - if [[ $(command -v apt-get) ]] ; then
      apt-get update -y -qq
      && apt-get install -y sq gpg-agent
      && apt-cache policy libgcrypt20 gpg-agent ;
      elif [[ $(command -v dnf) ]] ; then
      dnf install -y sequoia-sq gnupg ;
      elif [[ $(command -v apk) ]] ; then
      apk add --update sequoia-sq gnupg ;
      fi
    - gpg-agent --version
    - sq version
    - mkdir -p /run/user/$UID # For GnuPG's socket directories

# Modifications to the linux jobs:
check:
  before_script:
    - !reference [.gpg_agent, check]
    - !reference [.before_script, end] # Comes from common-ci

linux:
  before_script:
    - !reference [.gpg_agent, check]
    - !reference [.before_script, end] # Comes from common-ci

alpine-openssl:
  before_script:
    - !reference [.gpg_agent, check]
    - !reference [.before_script, end] # Comes from common-ci
