[package]
name = "sequoia-chameleon-gnupg"
version = "0.1.0"
authors = ["Justus Winter <justus@sequoia-pgp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
dirs = "3"
libc = "0.2"
sequoia-openpgp = "1.3"
thiserror = "1"
