[package]
name = "sequoia-chameleon-gnupg"
version = "0.1.0"
authors = ["Justus Winter <justus@sequoia-pgp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
base64 = "0.13"
chrono = "0.4"
dirs = "4"
home-dir = "0.1"
libc = "0.2"
sequoia-openpgp = "1.6"
sequoia-openpgp-mt = "0.1"
sequoia-ipc = "0.27"
thiserror = "1"

[dev-dependencies]
edit-distance = "2"
lazy_static = "1"
tempfile = "3"

[[bin]]
name = "sequoia-chameleon-gpg"
path = "src/gpg.rs"

[[bin]]
name = "sequoia-chameleon-gpgv"
path = "src/gpgv.rs"
